services:
  exchange-app-con-rabbit-incoming:
    profiles:
      - exchange-app-con-rabbit-incoming
      - all
    env_file:
      - ./exchange-build/package/env/common.env
      - ./exchange-build/package/env/con-rabbit.env
      - ./exchange-build/package/env/con-rabbit-incoming.env
    restart: on-failure
    build: 
      context: .
      dockerfile: ./exchange-app-con-rabbit-incoming/docker/use-jar.dockerfile
    image: exchange-app-con-rabbit-incoming
  exchange-app-con-rabbit-outgoing:
    profiles:
      - exchange-app-con-rabbit-outgoing
      - all
    env_file:
      - ./exchange-build/package/env/common.env
      - ./exchange-build/package/env/con-rabbit.env
      - ./exchange-build/package/env/con-rabbit-outgoing.env
    restart: on-failure
    build:
      context: .
      dockerfile: ./exchange-app-con-rabbit-outgoing/docker/use-jar.dockerfile
    image: exchange-app-con-rabbit-outgoing
  exchange-app-processor:
    profiles:
      - exchange-app-processor
      - all
    env_file:
      - ./exchange-build/package/env/common.env
      - ./exchange-build/package/env/processor.env
    restart: on-failure
    volumes:
      - C:\Repos\datafabric\mrsk-configuration\exchange-configuration:/exchange-settings
    build:
      context: .
      dockerfile: ./exchange-app-processor/docker/use-jar.dockerfile
    image: exchange-app-processor
  exchange-app-processor-api:
    profiles:
      - exchange-app-processor-api
      - all
    env_file:
      - ./exchange-build/package/env/common.env
      - ./exchange-build/package/env/processor-api.env
    ports:
      - 3005:9911
    restart: on-failure
    volumes:
      - C:\Bin\exchange-app-processor-api:/exchange-settings
    build:
      context: .
      dockerfile: ./exchange-app-processor-api/docker/use-jar.dockerfile
    image: exchange-app-processor-api
  exchange-app-con-sk11-outgoing:
    profiles:
      - exchange-app-con-sk11-outgoing
      - all
    env_file:
      - ./exchange-build/package/env/common.env
      - ./exchange-build/package/env/con-sk11-outgoing.env
    restart: on-failure
    build:
      context: .
      dockerfile: ./exchange-app-con-sk11-outgoing/docker/use-jar.dockerfile
    image: exchange-app-con-sk11-outgoing
  exchange-app-con-platform-outgoing:
    profiles:
      - exchange-app-con-platform-outgoing
      - all
    env_file:
      - ./exchange-build/package/env/common.env
      - ./exchange-build/package/env/con-platform-outgoing.env
    restart: on-failure
    build:
      context: .
      dockerfile: ./exchange-app-con-platform-outgoing/docker/use-jar.dockerfile
    image: exchange-app-con-platform-outgoing
  exchange-app-con-sk11-incoming:
    profiles:
      - exchange-app-con-sk11-incoming
      - all
    env_file:
      - ./exchange-build/package/env/common.env
      - ./exchange-build/package/env/con-sk11-incoming.env
    restart: on-failure
    build:
      context: .
      dockerfile: ./exchange-app-con-sk11-incoming/docker/use-jar.dockerfile
    image: exchange-app-con-sk11-incoming
  exchange-app-con-sk11-rest-incoming:
    profiles:
      - exchange-app-con-sk11-rest-incoming
      - all
    env_file:
      - ./exchange-build/package/env/common.env
      - ./exchange-build/package/env/con-sk11.env
      - ./exchange-build/package/env/con-sk11-rest-incoming.env
    restart: on-failure
    build:
      context: .
      dockerfile: ./exchange-app-con-sk11-rest-incoming/docker/use-jar.dockerfile
    image: exchange-app-con-sk11-rest-incoming
  exchange-app-con-sk11-nodes-incoming:
    profiles:
      - exchange-app-con-sk11-nodes-incoming
      - all
    build:
      context: .
      dockerfile: ./exchange-app-con-sk11-nodes-incoming/docker/use-jar.dockerfile
    image: exchange-app-con-sk11-nodes-incoming
  adapter-sandbox-app-sk-ping:
    profiles:
      - adapter-sandbox-app-sk-ping
      - all
    env_file:
      - ./exchange-build/package/env/common.env
      - ./exchange-build/package/env/con-sk11-outgoing.env
    build:
      context: .
      dockerfile: ./adapter-sandbox-app-sk-ping/docker/use-jar.dockerfile
    image: adapter-sandbox-app-sk-ping
  exchange-app-mail:
    profiles:
      - exchange-app-mail
      - all
    env_file:
      - ./exchange-build/package/env/common.env
      - ./exchange-build/package/env/mail.env
    restart: on-failure
    build:
      context: .
      dockerfile: ./exchange-app-mail/docker/use-jar.dockerfile
    image: exchange-app-mail
  exchange-app-con-meter-incoming:
    profiles:
      - exchange-app-con-meter-incoming
      - all
    env_file:
      - ./exchange-build/package/env/common.env
      - ./exchange-build/package/env/con-meter-incoming.env
    restart: on-failure
    build:
      context: .
      dockerfile: ./exchange-app-con-meter-incoming/docker/use-jar.dockerfile
    image: exchange-app-con-meter-incoming