# Use a Node 16 base image
FROM node:16-buster-slim AS build
# Set the working directory to /app inside the container
WORKDIR /app
# Copy app files
COPY . .
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm ci 
# Build the app
RUN npm run build

# Use a smaller base image for the final production image
FROM node:16-buster-slim
# Set the working directory to /app inside the container
WORKDIR /app
# Copy the built app from the build stage
COPY --from=build /app/build ./build
# Set the env to "production"
ENV NODE_ENV production
# Expose the port on which the app will be running (3000 is the default that serve uses)
EXPOSE 3000
# Install serve globally
RUN npm install -g serve
# Start the app
CMD [ "serve", "build" ]