# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

#deploy-adapter-app-rabbit-incoming:
#  stage: deploy
#  #  tags:
#  #    - shell-builder
#  rules:
#    - when: manual
#  script:
#    - "chmod -R 777 ./*"
#    - "docker build .  --file ./adapter-app-rabbit-incoming/docker/use-source.dockerfile  --tag 192.168.20.100:5000/adapter-app-rabbit-incoming:${IMAGE_TAG}"
#    - "docker push 192.168.20.100:5000/adapter-app-rabbit-incoming:${IMAGE_TAG}"
#
#deploy-adapter-app-rabbit-outgoing:
#  stage: deploy
#  #  tags:
#  #    - shell-builder
#  rules:
#    - when: manual
#  script:
#    - "chmod -R 777 ./*"
#    - "./gradlew adapter-app-rabbit-outgoing:jar"
#    - "docker build .  --file ./adapter-app-rabbit-outgoing/docker/use-jar.dockerfile  --tag 192.168.20.100:5000/adapter-app-rabbit-outgoing:$#{IMAGE_TAG}"
#    - "docker push 192.168.20.100:5000/adapter-app-rabbit-outgoing:${IMAGE_TAG}"
#
#deploy-adapter-app-sk11-outgoing:
#  stage: deploy
#  rules:
#   - when: manual
#  script:
#    - "chmod -R 777 ./*"
#    - "./gradlew adapter-app-sk11-outgoing:jar"
#    - "docker build .  --file ./adapter-app-sk11-outgoing/docker/use-jar.dockerfile --tag 192.168.20.100:5000/adapter-app-sk11-outgoing:${IMAGE_TAG}"
#    - "docker push 192.168.20.100:5000/adapter-app-sk11-outgoing:${IMAGE_TAG}"
#
#deploy-adapter-app-sk11-incoming:
#  stage: deploy
#  rules:
#    - when: manual
#  script:
#    - "chmod -R 777 ./*"
#    - "./gradlew adapter-app-sk11-incoming:jar"
#    - "docker build .  --file ./adapter-app-sk11-incoming/docker/use-jar.dockerfile --tag 192.168.20.100:5000/adapter-app-sk11-incoming:${IMAGE_TAG}"
#    - "docker push 192.168.20.100:5000/adapter-app-sk11-incoming:${IMAGE_TAG}"




deploy-processor:
  stage: deploy
  rules:
    - when: manual
  script:
    - "chmod -R 777 ./*"
#    - "./gradlew adapter-app-sk11-incoming:jar"
    - "docker build .  --file ./exchange-app-processor/docker/use-source.dockerfile --tag 185.98.82.237:5000/adapter-processor:${IMAGE_TAG}"
    - "docker push 185.98.82.237:5000/adapter-processor:${IMAGE_TAG}"

    
deploy-rabbit-incoming:
  stage: deploy
  rules:
    - when: manual
  script:
    - "chmod -R 777 ./*"
    - "docker build .  --file ./exchange-app-con-rabbit-incoming/docker/use-source.dockerfile --tag 185.98.82.237:5000/rabbit-incoming:${IMAGE_TAG}"
    - "docker push 185.98.82.237:5000/rabbit-incoming:${IMAGE_TAG}"
    

deploy-rabbit-outgoing:
  stage: deploy
  rules:
    - when: manual
  script:
    - "chmod -R 777 ./*"
    - "docker build .  --file ./exchange-app-con-rabbit-outgoing/docker/use-source.dockerfile --tag 185.98.82.237:5000/rabbit-outgoing:${IMAGE_TAG}"
    - "docker push 185.98.82.237:5000/rabbit-outgoing:${IMAGE_TAG}"


deploy-sk11-incoming:
  stage: deploy
  rules:
    - when: manual
  script:
    - "chmod -R 777 ./*"
    - "docker build .  --file ./exchange-app-con-sk11-incoming/docker/use-source.dockerfile --tag 185.98.82.237:5000/sk11-incoming:${IMAGE_TAG}"
    - "docker push 185.98.82.237:5000/sk11-incoming:${IMAGE_TAG}"

deploy-sk11-outgoing:
  stage: deploy
  rules:
    - when: manual
  script:
    - "chmod -R 777 ./*"
    - "docker build .  --file ./exchange-app-con-sk11-outgoing/docker/use-source.dockerfile --tag 185.98.82.237:5000/sk11-outgoing:${IMAGE_TAG}"
    - "docker push 185.98.82.237:5000/sk11-outgoing:${IMAGE_TAG}"

deploy-platform-outgoing:
  stage: deploy
  rules:
    - when: manual
  script:
    - "chmod -R 777 ./*"
    - "docker build .  --file ./exchange-app-con-platform-outgoing/docker/use-source.dockerfile --tag 185.98.82.237:5000/platform-outgoing:${IMAGE_TAG}"
    - "docker push 185.98.82.237:5000/platform-outgoing:${IMAGE_TAG}"


deploy-sk11-rest-incoming:
  stage: deploy
  rules:
    - when: manual
  script:
    - "chmod -R 777 ./*"
    - "docker build .  --file ./exchange-app-con-sk11-rest-incoming/docker/use-source.dockerfile --tag 185.98.82.237:5000/sk11-rest-incoming:${IMAGE_TAG}"
    - "docker push 185.98.82.237:5000/sk11-rest-incoming:${IMAGE_TAG}"

#cp-files-processor:
#  stage: deploy
#  #  tags:
#  #    - shell-builder
#  rules:
##    - when: manual
#  script:
#    - "docker build .  --file ./adapter-app-rabbit-incoming/docker/pipelines.dockerfile  --tag 192.168.20.100:5000/cp-files-rabbit-incoming:$#    - "docker push 192.168.20.100:5000/cp-files-rabbit-incoming:${IMAGE_TAG}"





#cp-files-rabbit-incoming:
#  stage: deploy
#  #  tags:
#  #    - shell-builder
#  rules:
#    - when: manual
#  script:
#    - "docker build .  --file ./adapter-app-rabbit-incoming/docker/pipelines.dockerfile  --tag 192.168.20.100:5000/cp-files-rabbit-incoming:${IMAGE_TAG}"
#    - "docker push 192.168.20.100:5000/cp-files-rabbit-incoming:${IMAGE_TAG}"

#cp-files-rabbit-outgoing:
#  stage: deploy
#  #  tags:
#  #    - shell-builder
#  rules:
#    - when: manual
#  script:
#    - "docker build .  --file ./adapter-app-rabbit-outgoing/docker/pipelines.dockerfile  --tag 192.168.20.100:5000/cp-files-rabbit-outgoing:${IMAGE_TAG}"
#    - "docker push 192.168.20.100:5000/cp-files-rabbit-outgoing:${IMAGE_TAG}"

#cp-files-sk11-outgoing:
#  stage: deploy
#  #  tags:
#  #    - shell-builder
#  rules:
#    - when: manual
#  script:
#    - "docker build .  --file ./adapter-app-sk11-outgoing/docker/mappings.dockerfile  --tag 192.168.20.100:5000/cp-files-sk11-outgoing:${IMAGE_TAG}"
#    - "docker push 192.168.20.100:5000/cp-files-sk11-outgoing:${IMAGE_TAG}"

#cp-files-sk11-incoming:
#  stage: deploy
#  #  tags:
#  #    - shell-builder
#  rules:
#    - when: manual
#  script:
#    - "docker build .  --file ./adapter-app-sk11-incoming/docker/mappings.dockerfile  --tag 192.168.20.100:5000/cp-files-sk11-incoming:${IMAGE_TAG}"
#    - "docker push 192.168.20.100:5000/cp-files-sk11-incoming:${IMAGE_TAG}"
